version: '3'
services:
  app-first:
    image: nest-smaller-docker-app-first
    build:
      context: .
      dockerfile: Dockerfile.first
      target: build
    ports:
      - 3000:3000

  app-second:
    image: nest-smaller-docker-app-second
    build:
      context: .
      dockerfile: Dockerfile.second
      target: deploy
    ports:
      - 4000:3000
