FROM node:18-alpine AS build

WORKDIR /usr/src/app

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --shamefully-hoist

COPY . .

RUN pnpm build

CMD [ "node", "dist/main.js" ]