FROM node:18-alpine AS build

RUN apk add --no-cache curl bash
RUN npm install -g pnpm
RUN curl -sfL https://gobinaries.com/tj/node-prune | bash -s -- -b /usr/local/bin

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --shamefully-hoist

COPY . .

RUN pnpm build

RUN pnpm prune --prod

RUN /usr/local/bin/node-prune

FROM node:18-alpine AS deploy

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package.json ./

CMD ["node", "dist/main.js"]
